/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.gva.edu.iesjuandegaray.valenbiciapiv2;

// Importamos las clases de conexion a mysql y los drivers de sql
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author laura
 */
public class ConexionBDD extends javax.swing.JFrame {

    // Declaramos la conexion a mysql
    private static Connection con;
    private static Statement s;
    private static DatosJSon dJSon;
    private static int numEst = 3;

    private static final String driver = "com.mysql.cj.jdbc.Driver";//com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "laura12345";
    private static final String url = "jdbc:mysql://localhost:3306/valenbicibd";

    /**
     * Creates new form ConexionBDD
     */
    public ConexionBDD() {
        initComponents();
        dJSon = new DatosJSon(numEst);
        jTextFieldNumEstaciones.setText("" + numEst);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1InstruccionNumeroEstaciones = new javax.swing.JLabel();
        jTextFieldNumEstaciones = new javax.swing.JTextField();
        jButtonObtenerDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1Conectar = new javax.swing.JButton();
        jButton2AnyadirBDD = new javax.swing.JButton();
        jLabel2DatosEstaciones = new javax.swing.JLabel();
        jLabel3EstadoConexion = new javax.swing.JLabel();
        jLabel4ConectarBDD = new javax.swing.JLabel();
        jButton3CerrarConexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1InstruccionNumeroEstaciones.setText("Introduce el número de estaciones a consultar:");

        jTextFieldNumEstaciones.setText("Num Estaciones");
        jTextFieldNumEstaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumEstacionesFocusLost(evt);
            }
        });
        jTextFieldNumEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumEstacionesActionPerformed(evt);
            }
        });

        jButtonObtenerDatos.setText("Datos");
        jButtonObtenerDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonObtenerDatosMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1Conectar.setText("Conectar");
        jButton1Conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1ConectarMouseClicked(evt);
            }
        });
        jButton1Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConectarActionPerformed(evt);
            }
        });

        jButton2AnyadirBDD.setText("Añadir a BDD");
        jButton2AnyadirBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2AnyadirBDDMouseClicked(evt);
            }
        });

        jLabel2DatosEstaciones.setText("Obtener Datos de Estaciones");

        jLabel3EstadoConexion.setText("Estado Conexión");

        jLabel4ConectarBDD.setText("Primero Obtener Datos de Estaciones y Conectar con BDD");

        jButton3CerrarConexion.setText("Cerrar conexión");
        jButton3CerrarConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3CerrarConexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1InstruccionNumeroEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jTextFieldNumEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonObtenerDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2DatosEstaciones)
                                    .addComponent(jLabel3EstadoConexion)
                                    .addComponent(jLabel4ConectarBDD)
                                    .addComponent(jButton3CerrarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2AnyadirBDD))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1InstruccionNumeroEstaciones))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonObtenerDatos)
                            .addComponent(jLabel2DatosEstaciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton1Conectar))
                    .addComponent(jLabel3EstadoConexion))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2AnyadirBDD)
                    .addComponent(jLabel4ConectarBDD))
                .addGap(54, 54, 54)
                .addComponent(jButton3CerrarConexion)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumEstacionesActionPerformed
        
    }//GEN-LAST:event_jTextFieldNumEstacionesActionPerformed

    private void jButton1ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConectarActionPerformed
        
    }//GEN-LAST:event_jButton1ConectarActionPerformed

    private void jButton1ConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1ConectarMouseClicked
        // TODO add your handling code here:
        conector();
        jButton2AnyadirBDD.setEnabled(true);
    }//GEN-LAST:event_jButton1ConectarMouseClicked

    private void jButtonObtenerDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonObtenerDatosMouseClicked
        // TODO add your handling code here:
        dJSon.mostrarDatos(numEst);
        jLabel2DatosEstaciones.setText("Datos de estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jButtonObtenerDatosMouseClicked

    private void jButton2AnyadirBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2AnyadirBDDMouseClicked
        // TODO Añade aquí el código para insertar los datos de una estación en la base de datos.
        try {
            String[] values = dJSon.getValues();

            for (String value : values) {
                if (value != null && !value.isEmpty()) {
                    String sql = "INSERT INTO historico "
                            + "(estacion_id, direccion, bicis_disponibles, anclajes_libres, estado_operativo, ubicacion) "
                            + "VALUES " + value;
                    s.executeUpdate(sql);
                }
            }
            jLabel3EstadoConexion.setText("Datos insertados correctamente");

        } //Si la conexion No fue exitosa mostramos un mensaje de error
        catch (SQLException e) {
            jLabel3EstadoConexion.setText("Error de conexion" + e);
        }

    }//GEN-LAST:event_jButton2AnyadirBDDMouseClicked

    private void jButton3CerrarConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3CerrarConexionMouseClicked
        // TODO Añade aquí el código para cerrar la conexión con la Base de datos.
        
         // Comprobamos si existe conexión y en ese caso la cerramos.
        try {
            if (con != null) { 
                con.close();
                jButton3CerrarConexion.setText("Conexión cerrada");
                jLabel3EstadoConexion.setText("Listo para establecer conexión");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConexionBDD.class.getName()).log(Level.SEVERE, null, ex);
            jButton3CerrarConexion.setText("Error al cerrar conexión: " + ex);
        }

    }//GEN-LAST:event_jButton3CerrarConexionMouseClicked

    private void jTextFieldNumEstacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumEstacionesFocusLost
        // TODO add your handling code here:
        numEst = Integer.parseInt(jTextFieldNumEstaciones.getText());
        dJSon.mostrarDatos(numEst);
        jLabel2DatosEstaciones.setText("Datos estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jTextFieldNumEstacionesFocusLost

    //Declaramos los datos de conexion a la bd
    public void conector() {
        //TODO Añade aquí el código para establecer la conexión con la base de datos

        try {
            Class.forName(driver);

            // Nos conectamos a la bd
            con = (Connection) DriverManager.getConnection(url, user, pass);
            s = con.createStatement();

            // Si la conexion fue exitosa mostramos un mensaje de conexion exitosa
            if (con != null) {
                jLabel3EstadoConexion.setText("Conexion establecida");
                jButton3CerrarConexion.setText("Cerrar conexión");
            }
        } // Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e) {
            jLabel3EstadoConexion.setText("Error de conexion" + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionBDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Conectar;
    private javax.swing.JButton jButton2AnyadirBDD;
    private javax.swing.JButton jButton3CerrarConexion;
    private javax.swing.JButton jButtonObtenerDatos;
    private javax.swing.JLabel jLabel1InstruccionNumeroEstaciones;
    private javax.swing.JLabel jLabel2DatosEstaciones;
    private javax.swing.JLabel jLabel3EstadoConexion;
    private javax.swing.JLabel jLabel4ConectarBDD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNumEstaciones;
    // End of variables declaration//GEN-END:variables
}
